### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by migmartri** [kubeapps/hub#44]
Apparently not showing correctly utf-8 chartset

![selection_334](https://user-images.githubusercontent.com/24523/34063550-9eeed0e8-e1a7-11e7-9614-7059a4775627.png)

**Comment by prydonius** [comment]
I've looked into this and confirmed the issue is client-side. The user data is encoded in base64 and saved in a cookie, when decoding this with Javascript's `btoa` function, we're losing the UTF-8 encoding. MDN documents a way to decode UTF-8 strings correctly https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding#The_Unicode_Problem.
